### ISSUE TITLE
Cannot attach multiple files to a message.

### ISSUE THREAD

**Issue by mechaHarry** [CiscoDevNet/webexteamssdk#105]
when attempting to pass multiple filenames as a list to the `files=` parameter in a message creation, I receive the following Error:

ValueError: The length of the `files` list is greater than one (1). The files parameter is a list, which accepts multiple values to allow for future expansion, but currently only one file may be included with the message.

Are there any plans to support multi file messaging?

**Comment by cmlccie** [comment]
@mechaHarry, good question.  This is a limitation of the [Messages Create API](https://developer.webex.com/docs/api/v1/messages/create-a-message).  I recommend reaching out to the Developer Support team in the ***#webex4devs*** Teams space or via the devsupport@webex.com e-mail address for roadmap questions.

**Comment by mechaHarry** [comment]
Thanks for pointing me in the right direction.

Just out of curiosity, from an implementation standpoint,
if and when the API decides to support multiple files via REST,
will your sourcecode need to be adjusted for this, or will it support it off the bat?

Thanks,
- mH

**Comment by cmlccie** [comment]
Right now we have a check in the SDK that verifies that only one item is in the list of files.  We do this so that we can provide an articulate error message about why there can only be one file attached to the message.  We can remove the check and allow the Webex Teams API to throw an error; doing so would allow the SDK to support multiple files as soon as the APIs do.
